### ISSUE TITLE
sus

### ISSUE THREAD

**Issue by KurumiFake** [hakunyannn/meow#1]
> [21:41:54] [Client thread/FATAL]: Error executing task
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_332]
> 	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_332]
> 	at net.minecraft.util.Util.runTask(Util.java:20) ~[meow.jar:?]
> 	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1089) ~[meow.jar:?]
> 	at net.minecraft.client.Minecraft.run(Minecraft.java:419) ~[meow.jar:?]
> 	at net.minecraft.client.main.Main.main(Main.java:113) ~[meow.jar:?]
> Caused by: java.lang.NullPointerException
> 	at net.minecraft.scoreboard.Scoreboard.removeTeam(Scoreboard.java:296) ~[meow.jar:?]
> 	at net.minecraft.client.network.NetHandlerPlayClient.handleTeams(NetHandlerPlayClient.java:1986) ~[meow.jar:?]
> 	at net.minecraft.network.play.server.S3EPacketTeams.processPacket(S3EPacketTeams.java:140) ~[meow.jar:?]
> 	at net.minecraft.network.play.server.S3EPacketTeams.processPacket(S3EPacketTeams.java:12) ~[meow.jar:?]
> 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[meow.jar:?]
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_332]
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_332]
> 	at net.minecraft.util.Util.runTask(Util.java:19) ~[meow.jar:?]
> 	... 3 more

**Comment by KurumiFake** [comment]
generic issue, idk

**Comment by KurumiFake** [comment]
getting an NPE whenever joining a server with scoreboard is kinda dumb tho
